myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), # <--- Admin Site
    path('', include('social.urls')), # <--- Social Dashboard
    path('', include("users.urls")), # <--- Users Dashboard
]

myproject/social/urls.py
# social/urls.py

from django.urls import path
from social.views import dashboard, profile_list, profile

app_name = "social"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
]

myproject/users/urls.py
# users/urls.py

from django.urls import path, include
from users.views import dashboard

app_name = "users"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", dashboard, name="dashboard"),
]

myproject/social/models.py
from typing import ClassVar
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user: ClassVar = models.OneToOneField(User, on_delete=models.CASCADE)
    follows: ClassVar = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    
    def __str__(self) -> str:
        return self.user.username


# Use decorator to Create a Profile for each new User.
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        # Can use set() instead of add() when need to add multiple references to an object
        # user_profile.follows.set([instance.profile.id])
        user_profile.follows.add(instance.profile)
        user_profile.save()


class Messages(models.Model):
    user: ClassVar = models.ForeignKey(
        User,
        related_name="messages",
        on_delete=models.DO_NOTHING,
    )
    body: ClassVar = models.CharField(max_length=140)
    created_at: ClassVar = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/social/forms.py
# social/forms.py

from django import forms
from .models import Messages

class MessageForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Post something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )

    class Meta:
        model = Messages
        exclude = ("user", )

myproject/social/views.py
# social/views.py

from django.shortcuts import render, redirect

from .models import Profile, Messages
from .forms import MessageForm


def dashboard(request):
    if not request.user.is_authenticated:
       return redirect('users:login')
    # Get form from request
    form = MessageForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.save()
            return redirect('social:dashboard')
    # Get all posts from followers and order by -created_at
    followed_messages = Messages.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")    
    
    return render(
        request,
        "social/dashboard.html",
        {"form": form, "messages": followed_messages},
    )


def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "social/profile_list.html", {"profiles": profiles})


def profile(request, pk):
    # Create profile for any user that doesnt have one
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()
    # Update followers for profile at pk in request URL
    profile = Profile.objects.get(pk=pk)
    if request.method =="POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == 'unfollow':
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    # Get follower, following, and message count
    follower_count: int = len(profile.follows.all())
    following_count: int = len(profile.followed_by.all())
    message_count: int = Messages.objects.filter(user_id=profile.user).count()
    return render(
        request,
        "social/profile.html",
        {
            "profile": profile,
            "follower_count": follower_count,
            "following_count": following_count,
            "message_count": message_count
        },
    )

myproject/users/views.py
# users/views.py

from django.shortcuts import render

def dashboard(request):
    return render(request, "users/dashboard.html")

myproject/social/templates/base.html
<!-- social/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>UBuh</title>
</head>
<body>
    <a href="{% url 'social:dashboard' %} ">
        <section class="hero is-small is-success mb-4">
            <div class="hero-body">
                <div class="level is-mobile">
                    <div class="level-left">
                        <h1 class="title is-1">Ubuh</h1>
                        <p class="subtitle is-4">
                            : Buh about it!
                        </p>
                    </div>
                    <div class="level-right">
                        {% if user.is_authenticated %}
                            <a class="button is-danger" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="button" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
    </a>

    <div class="container">
        <div class="columns">

            {% block content %}

            {% endblock content %}

        </div>
    </div>
</body>
</html>

myproject/social/templates/social/dashboard.html
<!-- social/templates/social/dashboard.html -->

{% extends 'base.html' %}

{% block content %}

<!-- Main Content -->
<div class="column">
    <!-- Messages -->
    {% for message in messages %}
        <div class="box">
            {{ message.body }}
            <span class="is-small has-text-grey-light">
                ({{ message.created_at }} by <a href="{% url 'social:profile' message.user.profile.id %}">{{ message.user.username }}</a>)
            </span>
        </div>
    {% endfor %}
</div>
<!-- Sidebar -->
<div class="column is-one-third">
    <!-- Link to All Profiles -->
    <div class="block">
        <a href="{% url 'social:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <!-- Link to User Profile -->
    <div class="block">
        <a href="{% url 'social:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <!-- Submit a Post -->
    <div class="block">
        <!-- Header -->
        <div class="block">
            <h2 class="title is-2">Add a Post</p>
        </div>
        <!-- Form -->
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Post
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

myproject/social/templates/social/profile.html
<!-- social/templates/social/profile.html -->

{% extends 'base.html' %}

{% block content %}
<!-- Main COntent-->
<div class="column">
    <div class="block">
        <!-- Profile Header -->
        <div class="level is-mobile">
            <!-- Profile Title -->
            <h1 class="level-left title is-1">
                {{profile.user.username|upper}}'s Posts
            </h1>
            <!-- Follow/Unfollow -->
            <form class="level-right" method="post" action="">
                {% csrf_token %}
                <div class="buttons has-addons">
                    {% if profile in user.profile.follows.all %}
                        <button class="button is-success is-static">Follow</button>
                        <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
                    {% else %}
                        <button class="button is-success" name="follow" value="follow">Follow</button>
                        <button class="button is-danger is-static">Unfollow</button>
                    {% endif %}
                </div>
            </form>
        </div>
        <!-- Profile Statistics -->
        <nav class="level is-mobile">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Posts</p>
                    <p class="title">{{ message_count }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Following</p>
                    <p class="title">{{ following_count }}</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Followers</p>
                    <p class="title">{{ follower_count }}</p>
                </div>
            </div>
        </nav>
    </div>
    <!-- List all Posts for Profile -->
    <div class="content">
        {% for message in profile.user.messages.all %}
            <div class="box">
                {{ message.body }}
                <span class="is-small has-text-grey-light">
                    ({{ message.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>
</div>
<!-- Sidebar -->
<div class="column is-one-third">
    <!-- List All Profiles Button -->
    <div class="block">
        <a href="{% url 'social:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <!-- List all Following -->
    <div class="block">
        <div class="panel is-success">
            <h3 class="panel-heading">
                Following:
            </h3>
            {% for following in profile.follows.all %}
                <a class="panel-block" href="{% url 'social:profile' following.id %}">
                    {{ following }}
                </a>
            {% endfor %}
        </div>
    </div>
    <!-- List all Followers -->
    <div class="block">
        <div class="panel is-success">
            <h3 class="panel-heading">
                Followers:
            </h3>
            {% for follower in profile.followed_by.all %}
                <a class="panel-block" href="{% url 'social:profile' follower.id %}">
                    {{ follower }}
                </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

myproject/social/templates/social/profile_list.html
<!-- social/templates/social/profile_list.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
        <!-- List all Profiles -->
        <div class="card">
            <a href="{% url 'social:profile' profile.id %}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.user.username }}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.user.username|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

myproject/users/templates/users/base.html
<!--users/templates/base.html-->

<h1>Welcome to Social Network</h1>

{% block content %}
{% endblock %}

myproject/users/templates/users/dashboard.html
<!--users/templates/users/dashboard.html-->
<!-- Can use 'users/base.html' to use users/templates/users/base.html -->
<!-- Can use 'base.html' to use social/templates/base.html -->
{% extends 'base.html' %}

{% block content %}
Hello, {{ user.username|default:'Guest' }}!

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}">Logout</a>
        <a href="{% url 'users:password_change' %}">Change password</a>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</div>
{% endblock %}